version: "3.2"
services:
  mysql-container:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306 # DockerComposeContainer 로 컨테이너 띄울때는 랜˚덤포트를 사용하는 것이 좋다 (충돌방지)